spring:
  application:
      name: CloudApiTwo

server:
  port: ${PORT:2225}

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka-domain}:2221/eureka/
  instance:
    hostname: ${spring.cloud.client.hostname}

