apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-zuul-deployment
  labels:
    app: cloud-zuul
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-zuul
  template:
    metadata:
      labels:
        app: cloud-zuul
    spec:
      containers:
      - name: cloud-zuul
        image: 15.164.195.107:30002/paastacp/cloud-zuul:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2226
        env:
        - name: config-domain
          value: cloud-config-deployment.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
        - name: eureka-domain
          value: cloud-eureka-deployment.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
        - name: zuul-domain
          value: cloud-zuul-deployment.paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas.svc.cluster.local
      imagePullSecrets:
        - name: msa-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-zuul-deployment
  labels:
    app: cloud-zuul
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
spec:
  ports:
  - nodePort: 32226
    port: 2226
    protocol: TCP
    targetPort: 2226
  selector:
    app: cloud-zuul
  type: NodePort
