apiVersion: v1
kind: ConfigMap
metadata:
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
  name: my-redis-config
data:
  redis-config: |
    maxmemory 20mb
---
apiVersion: v1
kind: Service
metadata:
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
  name: my-redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  namespace: paas-30d87e54-269e-4c6f-871c-19dfba7eeec9-caas
  name: my-redis 
  labels:
      app: redis
spec:
  containers:
  - name: my-redis 
    image: redis:latest
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
      name: redis
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: my-redis-config
        items:
        - key: redis-config
          path: redis.conf