spring:
  application:
    name: CloudConfig
  cloud:
    config:
      server:
        git:
#          uri:/Users/swmoon/Dev/Source/Config/SPRING-CLOUD-SAMPLE-CONFIG
          uri: ${uri}
#          username: ${username}
#          password: ${password}
#          basedir: target/config
          force-pull: true


server:
  port: ${PORT:8004}

management:
  security:
    enabled: false
